### ISSUE TITLE
[BE] Feat: 함께달리기 그룹 생성

### ISSUE THREAD

**Issue by Henry-Cha** [6QuizOnTheBlock/OurClass#104]
## ✒ Description

함께달리기 그룹 만드는 흐름
1. 방장과 멤버들 블루투스 사용하여 그룹만듬.
2. 방장이 화면에 뜨는 학생 선택.(선택한 학생id 서버로 전송)
3. 선택 당한 학생한테는 초대 수락/거부 -> 응답 다시 방장한테 전해주기
4. 삭제누르면 똑같이 서버로 id보내고 학생은 추방당했다고 이벤트.
5. 최종 그룹 생성 버튼

## ✅ Todo
- [x] SSE추가
- [x] 레디스 추가 
- [x] (방장) 그룹 대기방 생성
- [x] (방장) 학생 초대 보내기 (id받아서 해당 id에게 초대 sse전송)
- [x]  (멤버) 초대 응답 (응답 받아서 방장에게 sse전송, 수락시 대기방에 추가)
- [x]  (방장) 대기 멤버 추방 (id받아서 해당 id에게 추방 sse전송, 대기방에 삭제)
- [x]  (방장) 최종 방 생성 (대기방으로 그룹 생성, 멤버들에게 sse전송, 임시 대기방 삭제)
