### ISSUE TITLE
[BE] Feat:  기본 이미지 Entity 생성 및 기본 이미지 조회, 프로필 이미지 수정 API 조회 

### ISSUE THREAD

**Issue by dalcheonroadhead** [6QuizOnTheBlock/OurClass#106]
## ✒ Description

기본 이미지 Entity 생성 및 기본 이미지 조회, 프로필 이미지 수정 API 조회 

## ✅ Todo
- [x]  (1) 기본 이미지 ERD, Entity 작성, API 명세서 수정 
- [x]  (2)  회원가입 시 1,2,3,4 로 들어오면 관련 사진 경로 주도록 설정 
- [x]  (3)  기본이미지 변경 Cotroller, Service 로직 작성 
- [x]  (4)  기본 이미지 주는 로직 테스트 
- [x]  (5) 회원가입 시 기본 이미지로 했을 때 테스트 
- [x]  (6) Default 이미지 리스트 주는 로직 작성 
- [x]  (7) Default 이미지 리스트 주는 로직 테스트
