### ISSUE TITLE
[BE] Feat: 유저 FCM 토큰 저장 및 수정

### ISSUE THREAD

**Issue by HABINOH** [6QuizOnTheBlock/OurClass#110]
## ✒ Description
각 유저마다 FCM 토큰을 클라이언트에게 입력받아 저장 및 업데이트 합니다.

## ✅ Todo
- [x] Redis 사용해서 유저 FCM 토큰 저장
- [x] 수정된 FCM 토큰이 올 때 저장된 FCM 토큰이 있다면 새로 교체
- [x] FCM 토큰 유효기간 2달 설정

## 📚 Etc
**<문제점>**
1. Redis 를 처음써서 JPA에 상속받아서 쓸 지 Template을 사용해서 쓸 지 어떻게 해야하는지 몰랐음
2. Redis 저장 시 유효기간 설정할 때 long 으로 시간을 설정하려고 하였으나 이상한 byte 코드들도 함께 저장되어서 메모리를 사용량이 비정상적으로 사용됨.
3. 출력할 떄도 이상한 byte 코드들이 따라서 출력되었음.
---
**<해결>**
1. 팀원과 합의 후 Template을 사용하기로 결정 (Redis Util을 만들어서 Redis 관련 로직 담당 util을 만들었음)
관련 참고 블로그 [spring boot에 Redis 붙여보기](https://velog.io/@ililil9482/spring-boot%EC%97%90-Redis-%EB%B6%99%EC%97%AC%EB%B3%B4%EA%B8%B0)
2. 처음에 opsForValue().set(key(String), value(String), time(long)) 으로 입력을 받았음.
(수정 전)
![image](https://github.com/6QuizOnTheBlock/OurClass/assets/108309664/881c0b3c-ae03-4c9c-aecd-d256310ac52e)

이때, opsForValue().set() 메소드 내부 로직을 찾아보니 long 으로 사용하려면 4번쨰 매개변수에 시간 타입을 지정해줘야함.
3개의 매개변수를 사용하려면 Duration 타입을 사용해야하는 것을 확인 후 Duration 타입을 사용하여 해결함.
(내부 로직)
![image](https://github.com/6QuizOnTheBlock/OurClass/assets/108309664/6e80ba0f-a348-4c1e-8a9b-c536230ed79f)

(수정 후)
![image](https://github.com/6QuizOnTheBlock/OurClass/assets/108309664/dd41f046-0025-4da6-80a7-9b8340a8742d)
