### ISSUE TITLE
[AND] Feat: 공통 AppBar 생성

### ISSUE THREAD

**Issue by TRASALBY** [6QuizOnTheBlock/OurClass#13]
## ✒ Description
다양한 화면에서 공통으로 사용할 앱바를 생성합니다.

## ✅ Todo
- [x] 아이콘, 제목, 상태가 포함된 앱바를 생성 합니다.
- [x] 스크롤 상태에 따로 확대 축소가 가능합니다.
- [x] 페이지에 따라 앱바의 상태가 변경됩니다.

### 상태 1
![image](https://github.com/6QuizOnTheBlock/OurClass/assets/54586491/b4d22797-f69e-481d-b65f-194ccbc90304)
### 상태 2
![image](https://github.com/6QuizOnTheBlock/OurClass/assets/54586491/2e5d0c82-1237-4668-8e81-b6ea5281d50d)
### 상태3
![image](https://github.com/6QuizOnTheBlock/OurClass/assets/54586491/3f703fec-1661-4751-8eeb-1b991dcc739f)
### 상태 4 (디자인 변경 좌측 하단)
![image](https://github.com/6QuizOnTheBlock/OurClass/assets/54586491/f2a10007-1bdd-4cb0-b4da-0d1c713fa902)
