### ISSUE TITLE
[BE] Feat:  프로필 이미지 수정 API 구현 

### ISSUE THREAD

**Issue by dalcheonroadhead** [6QuizOnTheBlock/OurClass#132]
## ✒ Description

프로필 이미지를 바꿀 수 있는 API를 구현합니다.

## ✅ Todo
- [x] (1) Controller, Service 작성 
- [x] (2) Record, Mapper 학습
- [x] (3) Record, Mapper로 Service 구현
