### ISSUE TITLE
[BE] Feat: 자동 로그인 API 구현 (with Filter Customizing)

### ISSUE THREAD

**Issue by dalcheonroadhead** [6QuizOnTheBlock/OurClass#133]
## 회원관리 로직에 대한 최적화 고민
Spring Security 공식 문서와 블로그 글들을 참고하니, Spring은 기본적으로 세션 기반이라서, JWT 기반 API 서버를 만들 떄는
![전수민 포토폴리오 ver3](https://github.com/6QuizOnTheBlock/OurClass/assets/102154788/c86f8e04-fa59-4b03-97f8-cab3835d5a34)
다음과 같은 4개의 필터를 사용하지 않습니다. 따라서 저는 저희 프로젝트에 맞게, 시큐리티 필터들을 새롭게 만들고,
해당 자리를 대체하겠습니다. 또한 요청 별로, 필요없는 필터는 거치지 않도록 다음과 같이 구현 하겠습니다.
![image](https://github.com/6QuizOnTheBlock/OurClass/assets/102154788/d9c0fedf-a826-4a92-89d1-d5fdb7a0bcf1)

## ✅ Todo
- [x] (1) Auto Login을 어떻게 할 건지 설계하고 그림으로 그립니다. 
- [x] (2) 그에 맞게 Auto Login Filter를 작성합니다. 
- [x] (3) AutoLoginFilter를 Security에 장착합니다. 
- [x] (4) API가 잘 돌아가는지 확인 합니다.
