### ISSUE TITLE
[BE] design: Quiz 용 웹 View 와이어 프레임 작성 

### ISSUE THREAD

**Issue by dalcheonroadhead** [6QuizOnTheBlock/OurClass#137]
## ✒ Description

와이어 프레임 기반으로 바로 화면 그리겠습니다. 
유준이가 고른 컬러 따라가고, 디자인 잘 못하지만, 최대한 세련되게 그리겠습니다.

## ✅ Todo
- [x] (1) 피그마 작성법 익숙해지기.
- [x] (2) 참고할 깃허브 보며 와이어 프레임을 그립니다. 
- [x] (3) 와이어프레임 기반으로 API를 재작성합니다. 

## 📚 Etc

![image](https://github.com/6QuizOnTheBlock/OurClass/assets/102154788/493d48d3-85de-45ef-9b21-ec14cbdc316e)
