### ISSUE TITLE
[FE] Chore: 프론트엔드 기본 세팅   

### ISSUE THREAD

**Issue by dalcheonroadhead** [6QuizOnTheBlock/OurClass#138]
## ✒ Description

React + Vite 기반 프로젝트를 만들고, package.json, manifest.json 등 만들어서 프론트 엔드 기본 세팅을 합니다. 

## ✅ Todo
- [x] (1) react 기본 세팅
- [x] (2) Vite 기본 세팅
- [x] (3) Tailwind 기본 세팅 
- [x] (4) chadcn 기본 세팅
