### ISSUE TITLE
[AND] Design: 공통 UI 리소스 추가

### ISSUE THREAD

**Issue by ghddbwns9808** [6QuizOnTheBlock/OurClass#14]
## ✒ Description
여러 모듈에서 공통으로 사용될 UI 리소스를 추가합니다

## ✅ Todo
- [x] drawable 리소스 추가
- [x] color 리소스 추가
- [x] font 리소스 추가
