### ISSUE TITLE
[BE] Refactoring: 인증/인가 오류에 대한 예외처리를 백엔드 규칙에 따라서 바꿉니다. 

### ISSUE THREAD

**Issue by dalcheonroadhead** [6QuizOnTheBlock/OurClass#140]
## ✒ Description

Filter 레벨에서 예외가 생기다보니, 하빈이가 구현한 Exception Handler를 사용해도, 해당 내용이 Response에 정확히 반영되지 않는 문제를 발견, 
ErrorCode를 이용한 Filter용 Response 객체를 만들고, 해당 내용을 AuthenticationEntryPoint, AccessDeniedHandler에 넣어서, 구현해야한다.

## ✅ Todo
- [x] (1) Filter Response 수정
- [x] (2) 인증 / 인가 오류에 대한 예외 처리 전개도 그리기 
- [x] (2) AuthenticationEntryPoint 구현 
- [x] (3) AccessDeniedHandler 구현 
- [x] (4) 인증/ 인가 오류 일부러 내보고 테스트 

## 📚 Etc

![image](https://github.com/6QuizOnTheBlock/OurClass/assets/102154788/3b8550b3-02ae-42d6-812b-c6ebe9bcba15)
