### ISSUE TITLE
[BE] Feat&devOps: 채팅 기능 구현 & kafka Setting

### ISSUE THREAD

**Issue by HABINOH** [6QuizOnTheBlock/OurClass#156]
## ✒ Description
Kafka, Redis, Mongo DB, MySQL 을 이용하여 채팅 시스템을 구현합니다.

## ✅ Todo
- [x] kafka와 zookeeper 서버를 구축하고 의존성 주입을 합니다.
- [x] kafka, zookeeper 서버를 구동합니다.
- [x] WebSocket Config 를 작성하면서 엔드포인트 구독, 발송 설정
- [x] kafka Producer, Listener Config 작성
- [x] redis에 입장, 퇴장, 채팅방에 현재 있는 인원 반환 기능 구현
- [x] Client와 주고 받을 Message 객체 생성, MongoDB 저장 할 Entity 생성
- [x] 단체 생성 시 단체에 해당하는 채팅방 1개 생성하도록 로직 변경
- [x] Android 와 소켓 통신 확인, 메시지 통신 확인
- [x] ConstantUtil 생성 및 정의와 사용
- [x] Swagger 작성

## 📚 Etc <br>
**개요**<br>
- 처음으로 채팅을 맡아서 개발하게 되었는데, 기능 구현에 대해서 기술적으로 많은 고민이 있었습니다.
- 아래는 제가 고민 한 내용들입니다.

---

### 1. 채팅 데이터를 어떻게 주고 받을 것인가?
- HTTP Polling
서버와 연결을 맺고 있지 않고 API 개발로 간단하게 기능 구현이 가능하며 서버 리소스를 절약할 수 있다는 장점이 있습니다.
하지만, 주기적으로 메시지를 Client가 가져가는 방식이라 타 사용자가 전달하는 메시지가 수신하는 사용자까지 도달하는데 일정 시간 지연이 발생할 수 있고, Client 마다 Polling 되는 시점이 달라서 서로 보고 있는 메시지가 달라서 실시간으로 채팅을 주고 받을 때 단점이 있다고 생각해서 해당 방법을 채택하지 않았습니다.

- WebSocket
라이브 채팅 플랫폼이나 많은 개발자들이 선호하는 방식으로 서버와 연결을 맺어진 상태에서 메시지가 Send가 되면 즉시 전달할 수 있는 장점이 있습니다.
하지만, 서버와 연결이 지속되어야 하므로 서버가 처리할 수 있는 클라이언트의 수의 제한이 있습니다. 
그러나 HTTP Polling 방식의 단점이 거의 완벽에 가깝게 발생하지 않고
현재 저희 프로젝트에서는 **단체 채팅방이 주 목적인 관계로 모든 시점에서 단체가 보고 있는 채팅의 내용이 일치해야 하므로 WebSocket 방식을 채택**하였습니다.

_**메시지 프로토콜에 특화된 STOMP를 사용했습니다!**_

---

### 2. 외부 브로커를 사용할 것인가?
- 내부 브로커
![image](https://github.com/6QuizOnTheBlock/OurClass/assets/108309664/b2772f57-bffb-4444-913e-02d9de23610f)

-->> 내부 브로커는 확장성에 제한이 있고 대규모 사용자 기반을 지원하거나 메시지 처리 요구가 급증하는 경우, 성능 문제가 발생할 수 있고, 메시지 유실 가능성도 있어서 이왕 기능을 구현하는데 확장성과 성능적으로 좋게 개발하고 싶어서 내부 브로커 사용은 하지 않기로 했습니다.

<br><br><br>

- 외부 브로커
![image](https://github.com/6QuizOnTheBlock/OurClass/assets/108309664/61eee74f-691d-483a-a71e-cc59336afc26)

-->> 외부 브로커는 확장성과 선택하는 브로커에 따라서 기능 성능에 대한 각각의 장점이 존재하며, 메시지 유실 가능성도 적으며, 안정적인 데이터 송수신이 가능하여 외부 브로커 사용을 결정하고 **어떤 브로커를 사용하여 구축할 지 고민**하였습니다.

---

### 3. 외부 브로커 선택

( Redis Pub/Sub )

Redis 클러스터를 생성하여 운영할 수 있고, 메시지 전달이 매우 빠르다는 장점이 있습니다.
하지만, 대규모 트래픽에 대해서 처리하는 경우 클러스터 노드를 확장할수록 성능 저하가 발생할 수 있고, 채널의 구독자 수가 많아질수록 선형적으로 메시지 발행 속도도 지연된다는 점에서 선택하지 않고, 채팅방 입장 퇴장 기록만 하기로 했습니다.

<br><br>

**( Spring kafka )**

메시지 비휘발성으로 인해 메시지 **데이터 복구 용이성**과 **Transaction을 파워풀**하게 쓸 수 있어서 **강력한 데이터 관리**가 가능하고, 스트림 프로세서를 활용하여 **메시지 처리가 매우 뛰어나며** **확장성에 다른 시스템에 비해 좋은 성능**을 자랑하여 현재 많은 기업들이 실제로 사용하고 있는 **검증된 System인 만큼 사용을 결정**했습니다.

---

### 4. 채팅 메시지 저장 DB 선택

채팅 메시지를 영구적으로 저장한다는 가정하에 아래와 같은 조건을 고려해서 선택했습니다.

(1) 메시지의 수정/삭제는 없고, 저장/조회만 발생하는 것으로 가정
(2) 대량의 메시지를 빠르게 조회 할 수 있도록 해야함
(3) 추후 채팅 읽음 개수 처리를 고려해야함
<br>
위 고려 사항으로 RDB 보다는 NoSQL 이 더 잘 맞다고 판단하여 MongoDB를 선택했습니다.
<br>

#### **!!! 선택이유 !!!**

(1) Schemaless 한 특성을 통해 다양한 형식의 메시지를 유연하게 저장/관리할 수 있고, 

(2) 도큐먼트 형태로 계층적인 구조로 저장되어 메시지 내의 다양한 객체를 포함하여 저장이 가능하고 메시지 내의 모든 객체 간의 관계를 저장과 조회가 가능함

(3) 추후에 DB 데이터 관리에 대해서 Cloud 서비스가 제공되기 때문에 필요하다면 도입을 하여 관리 리소스를 줄일 수 있음

---

**참고 사이트**

[1] [[Spring Boot] STOMP를 이용한 실시간 채팅 및 채팅방 동적 생성](https://velog.io/@ygy0102/Spring-Boot-STOMP%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EC%8B%A4%EC%8B%9C%EA%B0%84-%EC%B1%84%ED%8C%85-%EB%B0%8F-%EC%B1%84%ED%8C%85%EB%B0%A9-%EB%8F%99%EC%A0%81-%EC%83%9D%EC%84%B1)
[2] [채팅 (STOMP + JWT)](https://velog.io/@jkijki12/%EC%B1%84%ED%8C%85-STOMP-JWT)
[3] [Apache Kafka에 Spring 사용 - Spring 공식 문서](https://docs.spring.io/spring-kafka/reference/kafka.html)
[4] [[Kafka KRU] Consumer 내부 동작 원리와 구현](https://devocean.sk.com/community/detail.do?ID=165478&boardType=DEVOCEAN_STUDY&page=1)
[5] [Stomp + Kafka를 이용한 채팅 기능 개발하기 - (with Spring Boot) #2 (Kafka 설치 + MongoDB & Stomp 설정)](https://velog.io/@ch4570/Stomp-Kafka%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EC%B1%84%ED%8C%85-%EA%B8%B0%EB%8A%A5-%EA%B0%9C%EB%B0%9C%ED%95%98%EA%B8%B0-with-Spring-Boot-2-Kafka-%EC%84%A4%EC%B9%98-MongoDB-Stomp-%EC%84%A4%EC%A0%95)
[6] [Spring Boot Web Chatting : 스프링 부트로 실시간 채팅 만들기(2) chatDTO, DAO, Socket.js 코드 알아보기](https://terianp.tistory.com/149)
[7] [JAVASCRIPT.INFO , Clinet 에서 Stomp 연결 방법 - js 공식문서](https://ko.javascript.info/websocket)
[8] [Spring boot Socket 공식문서](https://spring.io/guides/gs/messaging-stomp-websocket)

---

### MongoDB 시간 변환하기

- 밀리 세컨드 Time 을 Asia/Seoul 로 변환
Instant.ofEpochMilli(sendDateTime).atZone(ZoneId.of("Asia/Seoul")).toLocalDateTime()

- Asia/Seoul 시간을 밀리 세컨드로 변환
sendDateTime.atZone(ZoneId.of("Asia/Seoul")).toInstant().toEpochMilli();

---
