### ISSUE TITLE
[FE] Feat: Quiz 대기방 화면 구현 

### ISSUE THREAD

**Issue by dalcheonroadhead** [6QuizOnTheBlock/OurClass#213]
## ✒ Description

![image](https://github.com/6QuizOnTheBlock/OurClass/assets/102154788/5aa4c853-19be-42c5-8217-41dc576a1209)

1. 선생님이 안드로이드 화면 중 Quiz를 누른다. 
2. Quiz가 시작되고, 학급 학생들에게 접속 URL이 FCM 알림으로 간다 .
3. 알림을 받은 학생들이 퀴즈 URL을 누른다. 
4. URL에 쿼리 스트링으로 해당 유저의 Id를 같이 보낸다. 
5. 해당 id로 누군지 확인 후, 퀴즈 대기방에 전부 넣는다. 

까지 구현할 예정입니다. 
[이번 이슈는 대기방 화면 구성까지 하겠습니다. ]
![image](https://github.com/6QuizOnTheBlock/OurClass/assets/102154788/65c366ed-3e45-4444-8af5-d1b3467e74a5)

## ✅ Todo
- [x] 1. 대기방 화면을 GPT 한테 보여주고 조언을 얻느다.  
- [x] 2. 사용자의 프로필, 이름, 기다리는 중... 현재 들어온 인원을 알리는 화면을 만든다.
- [x] 3.  밑에 아바타 태그를 이용해, 사람들이 들어오면 (Socket subscribe를 하면 보이도록 만든다.)
- [x] 4. 더미값으로 되는지 확인한다. 
- [x] 5. 배경 화면을 꾸민다. 
- [x] 6. 본 블럭을 꾸민다. 
- [x] 7. 디테일을 잡는다.
