### ISSUE TITLE
[BE] Feat: 회원가입, 로그인 API 세분화 및 구현

### ISSUE THREAD

**Issue by dalcheonroadhead** [6QuizOnTheBlock/OurClass#22]
## ✒ Description

1. Spring Security를 이용해 `회원가입 로직`을 구현합니다. 
2. AND와 마추기 전, `기초 모형 작성 및 테스트`까지를 목표로 하고, AND와 연결하면서 생기는 오류 등은 `Bug Report`로 관리하겠습니다.

## ✅ Todo
- [x] (1) 회원가입 요청을 받는 Controller와 Service, Repository를 작성합니다. 
- [x] (2) Security Config와 JWT Auth Filter, JwtUtil 을 작성하고, 토큰이 제대로 만들어지는지 테스트 합니다. 
- [x] (3) 선생님 ROLE의 White List, 학생 ROLE의 White List를 따로 관리합니다.
- [x] (4) 로그인 API를 구현하고 테스트 합니다. 
- [x] (5) SWAGGER를 위한 명세를 합니다.
- [x] (6) AND에서 요청과 함께 보내준 Email이 기존 회원이면, 바로 `Access Token`과 `RefreshToken`을 건네줍니다.
- [x] (7) 신규 회원이라면, ROLE 을 `Guest`로 저장하고, 추가정보를 입력하라는 `Message`를 보냅니다.
- [x] (8) 추가정보 (직책, 프로필 이미지)를 받는 Cotroller와 해당 부분을 DB에 처리하는 Service, Repository Query를 작성하고 테스트 합니다.
- [x] (9) 백엔드 팀원들과 코드 리뷰 후 고치기
- [x] (10) User Flow 전개도를 그리고 코드에 대한 설명을 정리하여, 팀원들에게 전달합니다. 

## 📚 Etc

1. [Redis 활용해서 Refresh Token 관리](https://inkyu-yoon.github.io/docs/Language/SpringBoot/RefreshToken)
2. [@Indexed 어노테이션 사용 시 주의점](https://dkswnkk.tistory.com/709)
3. [공식 문서](https://docs.spring.io/spring-security/reference/getting-spring-security.html)
4. [개발자 유미 커리큘럼](https://www.youtube.com/@xxxjjhhh)
