### ISSUE TITLE
[BE] Feat: 자유게시판 글 작성 구현

### ISSUE THREAD

**Issue by HABINOH** [6QuizOnTheBlock/OurClass#23]
## ✒ Description
자유게시판 글 작성할 수 있는 API를 구현합니다.

## ✅ Todo
- [x] SNS domain에 controller, service, dto, repository를 구분 & 생성합니다.
- [x] Entity 관계를 확인하고 필요한 연관관계가 있다면 설정합니다.
- [x] 구현 후 Swagger에서 동작확인 후 DB에 정상적인 저장이 되는지 확인합니다.

## 📚 Etc
Multipart와 DTO를 함께 받는 것을 처음 해봐서 많은 에러를 겪었지만 해결했습니다.
**< 문제점 >**
1. dto 안에 multipart 형식을 같이 받았는데 @ ModelAtribute로 받으니 제대로 받지 못함
2. @ RequestBody 로 받으니 swagger에서 multipart에 대한 테스트를 할 수가 없는 형식(json)이라서 어려움을 겪음
3. @ RequestPart로 나눠서 받았는데 value를 지정하지 않아서 데이터가 제대로 들어오지 않는 에러가 발생

**< 해결 >**
@RequestPart로 나눠서 받고 value를 지정함으로써 Swagger에서 제대로 테스트를 해볼 수 있었다.

<참고 블로그>
[Spring Controller에서 MultipartFile, Dto를 함께 요청하기](https://velog.io/@songs4805/Spring-Controller%EC%97%90%EC%84%9C-MultipartFile-Dto%EB%A5%BC-%ED%95%A8%EA%BB%98-%EC%9A%94%EC%B2%AD%ED%95%98%EA%B8%B0)
