### ISSUE TITLE
[AND] Feat: 학생 학급 리스트 조회 및 학급 가입

### ISSUE THREAD

**Issue by ghddbwns9808** [6QuizOnTheBlock/OurClass#257]
## ✒ Description
학생 계정으로 로그인 하면 소속된 학급 리스트를 조회하고, 학급에 가입할 수 있습니다.

## ✅ Todo
- [x] 로그인 및 회원가입 성공 시 화면 전환
- [x] 소속된 학급의 리스트 조회
- [x] 새로운 학급에 가입
- [x] 프로필 화면 전환
- [x] 프로필 관련 질문
