### ISSUE TITLE
[BE] devOps: Front End 인프라 구축

### ISSUE THREAD

**Issue by HABINOH** [6QuizOnTheBlock/OurClass#281]
## ✒ Description
퀴즈 관련한 FrontEnd 인프라를 구축합니다.

## ✅ Todo
- [x] Jenkins gitLab webhook 설정
- [x] Jenkins Node JS 빌드 설정
- [x] Jenkins Credential 설정
- [x] Jenkins pipline 작성
- [x] deploy_fe.sh 작성
- [x] nginx 설정 변경

## 📚 Etc

제가 정리한 Front End 인프라 구축 방법입니다.
