### ISSUE TITLE
[BE] devOps: BackEnd 인프라 구축 (무중단 배포 Blue/Green)

### ISSUE THREAD

**Issue by HABINOH** [6QuizOnTheBlock/OurClass#282]
## ✒ Description
BackEnd 서버 인프라를 구축합니다.

## ✅ Todo
- [x] swap 메모리 설정 및 JDK 설치
- [x] docker 설치
- [x] jenkins 설치
- [x] Nginx 설치
- [x] https 설정
- [x] Jenkins gitLab webhook 설정
- [x] Docker Hub
- [x] Docker file 작성
- [x] Jenkins jdk 21 빌드 설정
- [x] Jenkins Credential 설정
- [x] Nginx 설정 변경 (무중단 배포)
- [x] Jenkins pipline 작성
- [x] deploy.sh 작성
- [x] docker-compose.ulvan8080,8081.yml 작성
- [x] MySql 구축 (운영, 개발)
- [x] MongoDB 구축 (운영, 개발)
- [x] Redis 구축 (운영, 개발)
- [x] 메타모스트 채널 알림 연동
- [x] 우분투 타임존 변경

## 📚 Etc

블로그 정리하기 전 메모장에 인프라 구축 과정에 정리했습니다.
관련 내용은 아래 TXT 파일을 참고.

인프라는 어떤 상황에서 에러가 발생할 지 예측이 안되서 힘들다... 하지만 해낸다!!!

정리한 블로그 URL 입니다.
[Gitlab, Jenkins, Docker, Docker Hub, Nginx, Blue-Green 무중단배포 CI/CD 구축 - 1](https://velog.io/@habins226/Gitlab-Jenkins-Docker-Docker-Hub-Nginx-Blue-Green-%EB%AC%B4%EC%A4%91%EB%8B%A8%EB%B0%B0%ED%8F%AC-CICD-%EA%B5%AC%EC%B6%95-1)
