### ISSUE TITLE
[BE] devOps: sonarQube 인프라 구축

### ISSUE THREAD

**Issue by HABINOH** [6QuizOnTheBlock/OurClass#285]
## ✒ Description
sonarQube를 도입하여 인프라 구축합니다.

## ✅ Todo
- [x] sonarQube 설치
- [x] sonarQube 정보 저장
- [x] Jenkins 설정
- [x] Jenkins pipline 작성
- [x] build.gradle 변경
- [x] gitlab webhook 설정
- [x] 최종 확인

## 📚 Etc

제가 정리한 SonarQube 구축 방법입니다.
