### ISSUE TITLE
[BE] Feat: 학생간의 관계 - 게시글, 댓글 Count 저장하기

### ISSUE THREAD

**Issue by HABINOH** [6QuizOnTheBlock/OurClass#295]
## ✒ Description
홍길동이 작성한 게시글에 김영희가 반응(댓글)을 했으면 Count
홍길동이 작성한 댓글에 김영희가 반응(댓글)을 했으면 Count

단,
한 게시물당 반응 1개만!  Count 합니다.
한 댓글당 반응 1개만!  Count 합니다.

관계 점수를 매길 때 가중치가 2순위이기 때문입니다. 

## ✅ Todo
- [x] 게시글 작성자는 자신의 게시글에 대한 댓글 작성 가능
- [x] 해당 게시글에 반응(댓글 작성)을 하였는지 확인
- [x] 해당 댓글에 반응(대댓글 작성)을 하였는지 확인
- [x] 메소드로 분리하여, 역할에 따라 코드를 구조화

## 📚 Etc

**<문제점>**
- 모든 조건 분기에 대해서 머릿 속으로만 생각하다보니 시간이 오래걸렸다...

**<해결>**
- 종이에 필요한 경우의 수(분기)를 적고, 분기마다 해야하는 과정을 작성하고, 
메소드로 분리하여 코드를 구조화 하여 보기 좋은 코드를 만들었습니다.
