### ISSUE TITLE
[BE] Feat: 카프카를 이용한 대기열 구현 

### ISSUE THREAD

**Issue by dalcheonroadhead** [6QuizOnTheBlock/OurClass#309]
## ✒ Description

카프카를 이용해 퀴즈에 참여한 사람들을 관리할 대기열을 구현합니다. 

## ✅ Todo
- [x] (1) 카프카 학습 - 개념에 대하여 공부하고 정리합니다. 
- [x] (2) 하빈이 카프카 관련 코드들을 보고, 어떤 식으로 구현되어 있는 것인지 확인하고 공부합니다.
- [x] (3) 카프카를 이용한 대기열 구현 프로젝트를 보고, 어떤 식으로 이루어지는지 확인합니다. 
- [x] (4) 프론트 화면에서는 어떤 식으로 표현할지 생각하고, 프로젝트를 봅니다. 
- [x] (5) 카프카를 이용한 대기열 구현을 견본 프로젝트를 보고 직접 해봅니다. 
- [x] (6) 테스트를 해보고 에러를 잡습니다. 
- [x] (7) 백엔드가 완성되면 프론트 화면을 구성합니다. 
- [x] (8) 로딩 중 화면을 만듭니다.
- [x] (9) 5명 동시 접속 시 , 대기열 화면이 나오도록 백엔드를 세팅합니다. 
- [x] (10) 브라우저 5개를 동시에 접속하며, 로딩 중 화면이 나오도록 합니다.
- [x] (11) 테스트 합니다.

## 📚 Etc

https://github.com/6QuizOnTheBlock/OurClass/assets/102154788/a5bc6391-98f6-4dd3-bea9-3af0d6d687cf
