### ISSUE TITLE
[AND] Feat: 함께 달리기 확인

### ISSUE THREAD

**Issue by TRASALBY** [6QuizOnTheBlock/OurClass#31]
## ✒ Description
현재 진행중인 함께 달리기를 확인하고 상세 조회 할 수 있습니다.

## ✅ Todo
- [x] 함께 달리기 목록 조회
- [x] 진행 중 달리기 상태 조회
- [x] 함께 달리기 상세 조회
