### ISSUE TITLE
[BE] Feat: 소외도(친밀도) 점수 계산

### ISSUE THREAD

**Issue by HABINOH** [6QuizOnTheBlock/OurClass#327]
## ✒ Description
학생 관계 점수를 기반으로 각 학생 마다의 관계 등수를 계산하고,
등수에 따른 가중치를 두고 각 학생의 소외도 등수와 점수를 계산해서 DB에 저장합니다.

## ✅ Todo
- [x] 전체 학생의 관계 점수에 대한 평균, 표준편차 계산
- [x] 개인 학생이 각 학생에 대한 점수에 대해서 전체 학생 표준 편차 값을 기준으로 점수 정규화
- [x] 정규화된 점수들의 평균을 계산하여 해당 멤버의 소외도 점수를 도출

### 초기 로직

- 처음에 단순히 학생들의 관계 점수를 등수로 나누어 가중치 적용해서 소외도를 계산하는 로직을 작성했었습니다.

```java
@Transactional
@Scheduled(cron = "0 0 4 * * *")
protected void calculateIsolationScores() {
    List<Member> members = memberRepository.findAll(); // 모든 멤버를 로드
    Map<Member, List<Double>> memberScores = new HashMap<>(); // 각 멤버별 관계 점수 목록

    for (Member member1 : members) {
        List<Double> scores = new ArrayList<>();
        for (Member member2 : members) {
            if (!member1.equals(member2)) {
                Relationship relationship = relationshipRepository.findByMembers(member1, member2);
                if (relationship != null) {
                    scores.add(relationship.getRelationPoint());
                }
            }
        }
        scores.sort(Collections.reverseOrder()); // 점수를 내림차순으로 정렬
        memberScores.put(member1, scores);
    }

    // 순위를 바탕으로 소외도 계산
    for (Map.Entry<Member, List<Double>> entry : memberScores.entrySet()) {
        Member member = entry.getKey();
        List<Double> scores = entry.getValue();
        double isolationScore = 0.0;
        int rank = 1;
        for (Double score : scores) {
            isolationScore += score / rank; // 점수를 등수로 나누어 가중치 적용
            rank++;
        }
        MemberOrganization memberOrg = memberOrganizationRepository.findByMember(member);
        memberOrg.setIsolationPoint(isolationScore);
        memberOrganizationRepository.save(memberOrg);
    }
}
```

### 문제점

- 위와 같은 로직으로 실행하면 멤버 1과 멤버 2가 서로만 친하고 다른 학생들과 점수가 낮아도 
둘 만 과도하게 점수를 높이면 비정상적으로 소외도 점수가 측정되는 것을 확인했습니다.

---

### 해결 로직

- 전체 학생의 관계 점수에 대한 평균, 표준편차 계산
- 개인 학생마다 각 학생에 대한 점수에 대해서 전체 학생 표준 편차 값을 기준으로 점수 정규화
- 정규화된 점수들의 평균을 계산하여 해당 멤버의 소외도 점수를 도출

위의 로직을 적용하면 
**전체 학생 집단에서 각 학생의 위치를 더 정확히 평가할 수 있고, 
각 학생의 소외도 점수가 전체 집단 내에서 어떻게 위치하는지를 보여줄 수 있습니다.**

---

**< 문제점 >**
- 표준편차 계산 과정에서 모든 점수가 동일할 때 0이 될 때 문제가 발생함.
- 표준편차가 0이면 정규화 과정에서 분모가 0이 되어 결과가 NaN (Not a Number)이 됩니다. 

---

**< 해결 >**
- 표준편차가 0이면 모든 정규화된 점수를 0으로 처리하여 문제를 해결했습니다.

---

```java
    @Transactional
    @Scheduled(cron = "0 30 3 * * *")
    protected void isolationScore() {
        List<Organization> organizations = organizationRepository.findAll();

        for (Organization organization : organizations) {
            List<MemberOrganization> memberOrganizations =
                memberOrganizationRepository.findAllByOrganizationOrderByMemberId(organization);
            List<Double> allScores = new ArrayList<>();

            // 전체 점수 수집
            for (MemberOrganization member : memberOrganizations) {
                allScores.addAll(retrieveScores(member, memberOrganizations, organization));
            }

            // 전체 점수의 평균과 표준편차 계산
            double mean = allScores.stream()
                .mapToDouble(Double::doubleValue)
                .average()
                .orElse(0.0);

            double stdDev = calculateStandardDeviation(allScores, mean);

            // 각 멤버의 점수 정규화 및 소외도 계산
            for (MemberOrganization member : memberOrganizations) {
                List<Double> scores = retrieveScores(member, memberOrganizations, organization);

                List<Double> normalizedScores;
                if (stdDev < 1e-10) { // 매우 작은 표준편차 처리
                    // 표준편차가 0일 때, 즉 모든 점수가 같을 때
                    // 모든 정규화 점수를 0으로 설정
                    normalizedScores = Collections.nCopies(scores.size(), 0.0);
                } else { // 정규화
                    normalizedScores = scores.stream()
                        .map(score -> (score - mean) / stdDev)
                        .toList();
                }
                // 소외도 점수 도출
                double isolationScore = normalizedScores.stream()
                    .mapToDouble(Double::doubleValue)
                    .average()
                    .orElse(0.0);

                updateIsolationScore(member, isolationScore);
            }
        }
    }

    private List<Double> retrieveScores(
        MemberOrganization member, List<MemberOrganization> memberOrganizations,
        Organization organization
    ) {
        List<Double> scores = new ArrayList<>();
        for (MemberOrganization otherMember : memberOrganizations) {
            if (!member.equals(otherMember)) {
                relationshipRepository.findByOrganizationIdAndMember1IdAndMember2Id(
                    organization.getId(),
                    member.getMember().getId(),
                    otherMember.getMember().getId()
                ).ifPresent(rel -> scores.add(rel.getRelationPoint()));
            }
        }
        return scores;
    }

    private double calculateStandardDeviation(List<Double> scores, double mean) {
        double variance = scores.stream()
            .mapToDouble(score -> Math.pow(score - mean, 2))
            .average()
            .orElse(0.0);
        return Math.sqrt(variance);
    }

    private void updateIsolationScore(MemberOrganization member, double isolationScore) {
        member.updateIsolationPoint(isolationScore);
        memberOrganizationRepository.save(member);
    }
```
