### ISSUE TITLE
[AND] Feat: 챌린지 기록 UI 개선

### ISSUE THREAD

**Issue by TRASALBY** [6QuizOnTheBlock/OurClass#349]
## ✒ Description
누락된 UI기능들을 개선합니다.

## ✅ Todo
- [x] 챌린지 개수 표시
- [x] 참여 그룹 표시
- [x] 챌린지 생성 네비게이션 수정

## 📚 Etc
