### ISSUE TITLE
[AND] Feat: 교사 홈 메인페이지 및 Navigation

### ISSUE THREAD

**Issue by SteelZoo** [6QuizOnTheBlock/OurClass#35]
## ✒ Description
![image](https://github.com/6QuizOnTheBlock/OurClass/assets/67748153/a3a6eff3-fccb-4dc3-831c-228852c49355)

교사 홈 메인 페이지 구성

## ✅ Todo
- [x] 교사 홈 메인페이지 구성
- [x] bottom nav bar 이동 적용
- [x] 상세페이지(bottombar tab 외 이동 적용)
