### ISSUE TITLE
[AND] Design: 선생님 app ui detail 작업

### ISSUE THREAD

**Issue by ghddbwns9808** [6QuizOnTheBlock/OurClass#372]
## ✒ Description
선생님 application ui detail 작업

## ✅ Todo
- [x] text style 수정
- [x] ContentItem 사이즈 수정
- [x] 게시판 ui 수정
- [ ] 채팅 카메라 icon 제거
- [ ] 소외도 점수 -> 등수 수정
