### ISSUE TITLE
[BE] Refactor: 코드스멜 리팩토링

### ISSUE THREAD

**Issue by Henry-Cha** [6QuizOnTheBlock/OurClass#386]
## ✒ Description

소나큐브 코드스멜 리팩토링

## ✅ Todo
- [x] 트랜잭셔널 메서드 public 선언
- [x] long타입 끼리 더하기
- [x] random객체 재사용가능하도록 선언
- [x] controller 응답객체 제네릭타입 명시
- [x] 상수들 상수유틸 클래스로 이동
- [x] 필요없는 주석 제거
- [x] 변수 네이밍컨벤션 준수
- [x] 불변객체 toList()로 만들기
- [x] 변수 인라인화
- [x] exist쿼리 원시타입 boolean 응답
- [x] Math.random대신 랜덤객체 사용
- [x] 불필요한 형변환 제거
- [x] 사용하지않는 의존성 제거
- [x] 불필요한 코드 제거
