### ISSUE TITLE
[BE] Refactor: Code Smell Refactoring

### ISSUE THREAD

**Issue by HABINOH** [6QuizOnTheBlock/OurClass#387]
## ✒ Description

SonarQube 에서 제시한 코드 냄새 개선입니다.

## ✅ Todo
- [x] 와일드 카드 제거 및 컨트롤러 메소드 명 변경
- [x] service 메소드 명을 좀 더 명확하게 수정
- [x] mapper 메소드 명 첫 시작을 소문자로 수정
- [x]  Post Query DSL limit 더하는 부분 long 으로 변경
- [x] 댓글 작성하기 부분 인지 복잡도 줄이기
- [x] userAccessUtil 반환 받아서 Exception 처리 하기
- [x] 게시글 수정에서 이미지 삭제 처리하는 부분 if문 처리하는 부분 primitive 타입으로 사용하기
- [x] userAccessUtil 반환 받고 예외 던지도록 수정
- [x] ConstantUtil private 생성자 추가
- [x] chatHandler switch 문 default 추가
- [x] chatHandler switch 쉼표로 통합
- [x] mapper 메소드 이름 첫 글자 소문자로 수정
- [x] chat, chatFilter 와일드 카드 변경
- [x] swaggerConfig AUTHORIZATION 상수화
- [x] FcmType 변수 이름 첫 시작 소문자로 수정
- [x] ConstantUtil 사용하지 않는 상수 제거
- [x] ChatHandler switch문 패턴매칭 람다식으로 변경
