### ISSUE TITLE
[BE] Feat: Member, Organization 정보 확인 및 검증 Util 구현 

### ISSUE THREAD

**Issue by HABINOH** [6QuizOnTheBlock/OurClass#44]
## ✒ Description
Token 값 기준으로 유저 정보를 가져오는 기능의 함수와 파라미터로 들어오는 단체 번호가 멤버가 속해있는지 검증하는 기능 함수 작성합니다.

## ✅ Todo
- [x] util 에 공통적으로 쓰일 Class 생성
- [x] Member 정보 가져오는 메소드 생성
- [x] Member 가 단체에 속해있는지 검증하는 메소드 생성
- [x] 최종 확인 및 테스트

## 📚 Etc
많은 도메인에서 유저 검증이나 단체 검증을 중복적으로 사용하는데 util 에 함수로 공통적으로 쓸 수 있게 만들면 매우 가독성과 효율성이 높아진다는 것을 다시 한 번 상기했다.
