### ISSUE TITLE
[AND] Feat: Network 구조 setting

### ISSUE THREAD

**Issue by ghddbwns9808** [6QuizOnTheBlock/OurClass#45]
## ✒ Description
API response 대응 로직

## ✅ Todo
- [x] ApiResult Failure sealed class 정의
- [x] 안정적인 ApiResult getOrThrow 로직
- [x] HttpException 분류 및 data class 화
- [x] ApiResultCallAdapter Failure class 매핑
