### ISSUE TITLE
[BE] Feat: 게시글 수정 기능 변경

### ISSUE THREAD

**Issue by HABINOH** [6QuizOnTheBlock/OurClass#50]
## ✒ Description
게시판 수정 기능 변경합니다.
1. request dto 변경 (image 삭제 여부 boolean 추가)
2. 게시판 수정 시 boolean 값 여부로 확인해서 이미지 삭제
3. 게시판 수정 시 multipart 가 새로 들어오면 이미지 수정
4. 게시판 수정 시 multipart 가 아무것도 입력으로 오지 않으면 글만 수정 (이미지 수정 X)
5. Swagger Docs 정보 변경합니다.

## ✅ Todo
- [x] request dto boolean 값 추가합니다.
- [x] 조건에 맞는 분기에 따라 게시판 수정 로직을 변경합니다.
- [x] 기존에 hax 값으로 이미지 동일 여부를 판단한 로직을 삭제합니다.
- [x] swagger docs 정보 변경합니다.

## 📚 Etc

**<문제점>**
- Client 에서 Multipart 를 계속 주려면 S3 이미지 파일을 다운 받아서 요청해야해서 별로 좋지 않은 흐름이 발생

**<해결>**
- 게시판 수정에 관해 각각 해당하는 분기에 따라 이미지를 고려해서 게시판을 수정함
- description에 설명한대로 로직을 변경하면서 해결되었습니다.
