### ISSUE TITLE
[BE] Feat: 게시글 상세조회 구현

### ISSUE THREAD

**Issue by HABINOH** [6QuizOnTheBlock/OurClass#57]
## ✒ Description
pk에 해당하는 게시글과 댓글, 대댓글을 상세 조회 합니다.

## ✅ Todo
- [x] controller, dto, service, serviceImpl, mapper, QueryDSL 생성합니다.
- [x] 게시글을 조회 할 수 있는 멤버인지 검증합니다. (단체에 속해있는지)
- [x] 게시글 조회에 필요한 Data를 QueryDSL 을 활용하여 select 하는 로직을 작성합니다.
- [x] mapStruct 활용하여 dto 를 매핑합니다.
- [x] 게시글 상세 조회에 필요한 Data를 가공(댓글 작업)하여 반환합니다.
- [x] 구현 후 테스트와 확인을 합니다.

## 📚 Etc
**<문제점>**
1. MapStruct를 처음 써봐서 Data 끼리의 매핑 관계를 생각한다고 많은 시간이 걸림
2. QueryDSL을 처음 써봐서 QueryDSL 문법을 찾아보면서 작성한다고 많은 시간이 걸림

**<해결>**
1. MapStruct 관련해서 ChatGPT 에게 기본적인 정보를 검색하고 학습하여 구현함.
참고 블로그 : [MapStruct](https://yarisong.tistory.com/70)

2. QueryDSL은 같은 팀원이 이미 작성해놓은 작성법을 참고하여 공부하면서 구현함.
참고 블로그 : [QueryDSL](https://new-age-jh.tistory.com/295)
