### ISSUE TITLE
[BE] Feat: OIDC 기반 소셜 로그인 구현 

### ISSUE THREAD

**Issue by dalcheonroadhead** [6QuizOnTheBlock/OurClass#58]
## ✒ Description

OIDC 기반 소셜 로그인 구현 

<전개도>
![image](https://github.com/6QuizOnTheBlock/OurClass/assets/102154788/f926b4d9-e248-4e9c-93d6-6fcc83e4221a)

<open Id 토큰 받았을 때>
![KakaoTalk_20240430_012014477](https://github.com/6QuizOnTheBlock/OurClass/assets/102154788/825a7f86-ac9b-46a0-8668-9093f4fce45e)

<open Id 안을 까보면...> 
![KakaoTalk_20240430_012033225](https://github.com/6QuizOnTheBlock/OurClass/assets/102154788/85ae2fdc-6506-4867-a9b9-4caf7de62efb)

## ✅ Todo
- [x] (1) 비즈앱 개인 개발자 전환 -> 이메일도 동의사항에 포함하기 
- [x] (2) 클라이언트로부터 Open ID 토큰 받기
- [x] (3) Feign Client 공부 및 실습 해보기  (우리 프로젝트에서)
- [x] (4) Open ID 받아서 유효성 검증 및 토큰 디코딩 해서 정보 빼오는 로직 짜기
- [x] (5) Feign Client 적용해서 Kakao로부터 open Id-token 공개 키값 얻어오기 
- [x] (6) Open ID 헤더랑 페이로드 열어서 콘솔에 찍어보기 
- [x] (7) Open ID 검증 로직 구현 전개도 작성 
- [x] (8) 카카오 디코딩용 공개 키 재료 modulus, exponent 받기 해당 modulus와 exponent 조합으로 유효성 검증 RSA 키 만들기
- [x] (9) 유효성 검증 하기 
- [x] (10)  DTO 전부 Open ID 받는 것으로 고치기 

## 📚 Etc
1. [블로그 참조](https://kakao-tam.tistory.com/130)

### (1) Native APP 과 서버 통신 시 문제점 

Native APP은 소셜 로그인 시 소위 SDK 라는 라이브러리를 사용할 수 있습니다. 해당 SDK는 인증 서버 회사로부터 AccessToken과 RefreshToken을 한 번에 다 받을 수 있습니다. 당연히 그걸로 리소스 서버에 자원들을 활용할 수도 있고요. 따라서 서버에서는 역할이 좀 더 편해지는데요. 하지만 다음과 같은 의문이 들 수 있습니다.

#### 그러면 Native APP을 통해 들어온 이메일과 이름이 진짜 소셜 로그인을 거쳤다는 것을 서버에서는 어떻게 확인하나요? 

SDK 기반으로 네이티브 앱에서 다 처리해 버리면 당연히 서버에서는 해당 내용을 검증하지 못합니다. 해당 내용을 검증하려면 Open ID Connect 기반 로그인을 해야합니다. 

### (2) Open ID Connect 란 무엇인가요? 

개방형 표준 및 분산 인증 프로토콜로서 **인증**에 특화되어있습니다. 서버에서 신원정보를 비밀키로  인코딩한 ID토큰을 클라이언트에게 줍니다. 클라이언트는 자신의 신원을 증명해야할 서버들에게 해당 토큰을 건네줍니다. 
  해당 토큰은 무조건 인증 서버에서 제공하는 공개키로만 유효성 검증을 할 수 있는데, 이를 통해, 토큰의 변위조 여부를 체크할 수 있고, payLoad와 Header를 통해 어느 인증서버에서 인증 받았고, 무엇을 목적으로 발급되었는지, 간단한 신원정보가 무엇인지를 체크할 수 있습니다. 
**OAtuth2.0**는 **인가**에 특화된 프로토콜로써, 종국에 받은 AccessToken과 RefreshToken으로 Resource Server에 어떤 자원을 요청하기 위함입니다. 
OAuth2.0이 호텔 키라면, OIDC는 주민등록증이라고 생각하시면 됩니다. 

⭐ OIDC의 장점

1. 인증 서버와의 통신 작업이 OAuth2.0에 비해서 훨씬 간소해졌다. -> 속도 측면에서 성능이 좋다. 
2. Resource Sever를 쓰지 않는, 오직 인증용으로 소셜 로그인이 필요한 경우 Open ID 하나만 관리하면 되어서 인증 및 Client Sever 보안에 훨씬 용이 하다.

### (3) 순서

![image-20240501221546464](https://github.com/6QuizOnTheBlock/OurClass/assets/102154788/fcb7c294-a339-4495-b9b8-10852ba6721a)

       1. 서버에서 각 회원마다 고유한 값을 서버 내 비밀키로 전자서명한 후 Base64 인코딩 하여 JWT 토큰을 만듭니다. (이하 id-token) 
       2. 모바일 앱에서 고유한 ID-Token을 받습니다.
       3. 해당 토큰을 신뢰하는 서버에게 건네줍니다.
       4. 서버에서는 해당 토큰을 Base 64 디코딩 해서 헤더와 페이로드를 열어봅니다.
       5. 해당하는 곳에, 클라이언트 서버의 주소, 발급자, 해당 토큰을 유효성 검증할 수 있는 공개키의 id(이하 kid)가 주어집니다.
       6. 카카오 서버로부터 공개키 리스트를 받아서 그 중에 우리 서버에서 쓸 공개키를 빼옵니다.
       7. 해당 키로 Open id 검증을 합니다. 
       8. 유효한 Open id라면 payLoad에 적혀있는 이메일, 이름 등을 사용하면 됩니다.

## 3. 로그인, 회원가입 로직

![image-20240501222835536](https://github.com/6QuizOnTheBlock/OurClass/assets/102154788/fdba4d9f-ad12-4691-ab92-ce2a8daed2d9)

## 4. OIDC 소셜 로그인 구체적 로직

![image-20240501222901454](https://github.com/6QuizOnTheBlock/OurClass/assets/102154788/75b66ec0-8913-492f-805a-886cc490e2d3)
