### ISSUE TITLE
[AND] Feat: 안드로이드 프로젝트 세팅

### ISSUE THREAD

**Issue by TRASALBY** [6QuizOnTheBlock/OurClass#6]
## ✒ Description
안드로이드 기본 모듈 생성

## ✅ Todo
- [x] 프로젝트 생성
- [x] 기본 모듈 생성
- [x] 의존 관계 설정
- [x] 컨벤션 플러그인 생성
- [x] Hilt 적용
