### ISSUE TITLE
[And] Feat: 함께 달리기 확인 로직 구현

### ISSUE THREAD

**Issue by TRASALBY** [6QuizOnTheBlock/OurClass#61]
## ✒ Description
함께 달리기 목록 조회, 상세 조회 내부 로직을 구현 합니다.

## ✅ Todo
- [x] 목록 조회 api 연동
- [x] 목록 페이징 구현
- [x] 홈 -> 목록, 목록 -> 상세 조회 화면이동 구현
