### ISSUE TITLE
[BE] Feat: 게시글 댓글 작성 구현

### ISSUE THREAD

**Issue by HABINOH** [6QuizOnTheBlock/OurClass#70]
## ✒ Description
게시글에 해당하는 댓글을 작성할 수 있는 기능을 개발하겠습니다.

## ✅ Todo
- [x] 필요한 비지니스 로직에 해당하는 Java 파일을 생성합니다.
- [x] 필요한 mapper와 dto 생성합니다.
- [x] 비지니스 로직을 작성합니다.
- [x] 구현 완료 후 테스트와 검증합니다.
- [x] Swagger 작성합니다.

## 📚 Etc
**<문제점>**
- Swagger 에 아래에 해당하는 명령처럼 name와 value의 이름이 다를 떄 PathVariable이 Swagger에서 나타나지 않음

@ Parameter(name = "orgId", description = "단체 PK 값", required = true, in = ParameterIn.PATH) 
@ PathVariable(value = "id") Long id,

---

**<해결>**
- Parameter name 속성 값과 RequestParam의 속성 값을 동일하게 설정함으로써 해결하였습니다.

@ Parameter(name = "id", description = "단체 PK 값", required = true, in = ParameterIn.PATH) 
@ PathVariable(value = "id") Long id,
