### ISSUE TITLE
[AND] Feat: 회원가입

### ISSUE THREAD

**Issue by ghddbwns9808** [6QuizOnTheBlock/OurClass#79]
## ✒ Description
회원가입 기능을 구현합니다

## ✅ Todo
- [x] 역할 선택 ui
- [x] 프로필 사진 선택 ui
- [x] 회원가입 로직
- [x] 성공시 토큰 저장 및 화면 전환
