### ISSUE TITLE
[BE] Feat: 알림장 작성, 게시글(알림장) 삭제 & mapStruct 리팩토링

### ISSUE THREAD

**Issue by HABINOH** [6QuizOnTheBlock/OurClass#92]
## ✒ Description
게시글 작성과 수정하는 부분을 mapStruct 사용하는 것으로 리팩토링 하겠습니다.
게시글 작성 부분에서 알림장 작성도 통합해서 작업을 처리하는 것을 고려해서 로직을 작성하겠습니다.
게시글 삭제 부분에서 댓글 삭제 권한과 동일하게 코드를 리팩토링 하겠습니다.

## ✅ Todo
- [x] 게시글 작성, 수정에서 mapStruct 사용하는 것으로 변경
- [x] 게시글 작성 (write) 에서 알림장을 작성할 수 있는 권한을 선생님만 작성할 수 있도록 합니다.
- [x] 게시글 삭제 권한을 댓글 삭제 권한과 동일한 로직으로 리팩토링합니다.

## 📚 Etc

**<문제점>**
- 리팩토링 과정에서 Entity를 불변 객체로 사용하려고 @ Setter를 지우고 사용하려다가 
mapStruct 사용하는 부분에서 엔티티에 @ Setter 어노테이션을 지워서 매핑이 되지 않는 에러가 발생
---
**<해결>**
- ChatGPT를 활용하여 mapStruct 매핑 관련 부분을 알아보던 중 아래와 같은 정보를 확인하고 @ Setter를 붙여서 해결
- Image 엔티티의 Setter 메소드: ImageMapper가 내부적으로 Image 객체의 필드를 직접 수정하려면, 
해당 필드에 대한 setter 메소드가 Image 클래스에 정의되어 있어야 합니다. 
만약 Image 클래스가 불변 객체로 설계되었거나 setter가 없다면, MapStruct는 필드를 업데이트할 수 없습니다.
