### ISSUE TITLE
[BE] Feat: 게시글, 댓글 신고 - FCM Setting 포함

### ISSUE THREAD

**Issue by HABINOH** [6QuizOnTheBlock/OurClass#97]
## ✒ Description
게시글과 댓글 신고하기 기능을 구현하겠습니다.
게시글과 댓글을 신고하면 단체 담당자에게 알림이 전송됩니다. (FCM)

## ✅ Todo
- [x] FCM json 파일 .ignore 추가
- [x] 인프라 FCM json 파일 추가해서 빌드하도록 수정
- [x] FCM Config 및 Util 작성
- [x] 게시글 신고 시 단체 담당자에게 알림이 전송됩니다. (FCM)
- [x] 댓글 신고 시 단체 담당자에게 알림이 전송됩니다. (FCM)
- [x] 알림 목록에 신고에 대한 정보 저장
- [x] 로직 작성 후 테스트 확인 및 검증

## 📚 Etc
**<문제점>**
1. IntelliJ 업데이트 후 갑자기 빌드 안되는 에러
2. FCM 사용 방법에 대한 고민 (HTTP, SDK)
3. FCM Config 에서 Bean 등록과 PostStruct 사용의 고민
4. 많은 사용자에게 동시에 FCM 보낼 시 순차적 방법이 아닌 비동기적 방법에 대한 고민
5. FCM 전송 실패 시 에러 로직에 관한 고민
6. FCM Util의 범용성, 유연한 사용에 대한 고민
---
**<해결>**
1. [빌드 에러 해결 방법 블로그](https://velog.io/@chominho96/Spring-Intellij-Intellij-IDEA-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%8B%9C-Command-line-is-too-long-%EC%97%90%EB%9F%AC-%ED%95%B4%EA%B2%B0)

2. SDK 방식으로 결정
이유 : SDK는 인증, 에러 처리, 네트워크 통신 등을 자동으로 처리하며, API와의 일관성을 유지하기 쉽기 때문

3. Bean 등록으로 결정
이유 : 스프링의 DI 컨테이너가 자동으로 의존성을 주입하고, 필요한 곳에서 언제든지 인스턴스를 재사용할 수 있게 하며 스프링의 관리 하에 있기 때문에 성능과 관리 측면에서 이점을 갖기 떄문

4. @ Async 어노테이션을 사용하여 비동기로 동작 - ThreadPoolTaskExecutor 설정을 하였음

5. 지수 백오프 전략을 채택
지수 백오프(exponential backoff) 전략 : 네트워크 요청 실패 후 재시도 간격을 지수적으로 증가시키는 방법

6. FCM DTO 를 만들고 이에 FCM 전송하는 로직을 각 메소드로 분리하여 유연성 있게 사용할 수 있도록 함

---

### FCM Setting 방법입니다.

[자율 FCM 구축 (서버).txt](https://github.com/6QuizOnTheBlock/OurClass/files/15285565/FCM.txt)
